##version: '3'
##
##services:
##  web:
##    build: .
##    command: python manage.py runserver 0.0.0.0:8000
##    volumes:
##      - .:/app
##    ports:
##      - "8000:8000"
##    networks:
##      - main
##
#  celery-worker:
#    build: .
#    command: celery -A notification worker -l info
#    volumes:
#      - .:/app
#    environment:
#      - DJANGO_SETTINGS_MODULE=notification.settings
#    depends_on:
#      - redis
##
##  celery-beat:
##    build: .
##    command: celery -A notification beat -l info
##    volumes:
##      - .:/app
##    environment:
##      - DJANGO_SETTINGS_MODULE=notification.settings
##    depends_on:
##      - redis
##  nginx:
##    image: nginx:alpine
##    restart: always
##    networks:
##      - main
##    depends_on:
##      - web
##    ports:
##      - "80:80"
##      - "10080:80"
##      - "10443:443"
##    volumes:
##      - ./nginx.conf:/etc/nginx/nginx.conf
##
##
#  redis:
#    image: "redis:alpine"
##
##networks:
##  main:
#
#version: '3'
#
#services:
#  django:
#    build: .
#    ports:
#      - 8000:8000
#
#  nginx:
#    image: nginx
#    ports:
#      - 80:80
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - static:/app/static
#    depends_on:
#      - django
#
#volumes:
#  static:

version: '3'

services:
  django_gunicorn:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - static_files:/app/staticfiles
      - ./static:/static

  nginx:
    build: ./nginx
    volumes:
      - swap-face.xyz.cert:/etc/nginx/certificate.cert
      - swap-face.xyz.key:/etc/nginx/certificate.key
      - ./swap-face.xyz.cert:/etc/nginx/ssl/cert.pem
      - ./swap-face.xyz.key:/etc/nginx/ssl/key.pem
      - static_files:/app/staticfiles
      - ./static:/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django_gunicorn

  celery-worker:
    build: .
    command: celery -A notification worker -l info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=notification.settings
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A notification beat -l info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=notification.settings
    depends_on:
      - redis

  redis:
    image: "redis:alpine"

volumes:
  static:
  swap-face.xyz.cert:
  swap-face.xyz.key:
  static_files:

