# Generated by Django 3.2.13 on 2023-01-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
