# Generated by Django 3.2.13 on 2023-02-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
