# Generated by Django 3.2.3 on 2023-02-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_historyarticletask'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='revoke',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='task_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
